version: "3.9"

services:
  prometheus:
    container_name: "prometheus"
    image: "prom/prometheus:latest"
    volumes:
      - "./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - "prometheus-grafana-demo-network"

  grafana:
    container_name: "grafana"
    image: "grafana/grafana-oss:latest"
    volumes:
      - "grafana-storage:/var/lib/grafana"
    ports:
      - "3000:3000"
    networks:
      - "prometheus-grafana-demo-network"
    environment:
      # See: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  app:
    container_name: "app"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - POETRY_VERSION=1.1.14
    ports:
      - "8080:8080"
    networks:
      - "prometheus-grafana-demo-network"

volumes:
  grafana-storage:

networks:
  prometheus-grafana-demo-network:
    driver: bridge
