global:
  # How often Prometheus will scrape targets
  scrape_interval: 15s
  # How often Prometheus will evaluate rules
  evaluation_interval: 15s 

rule_files:
  # - "first.rules"
  # - "second.rules"

# What resources Prometheus monitors
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
